language: cpp
sudo: false
matrix:
  include:
  - os: osx
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
    env:
    - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-8
    env:
    - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
before_install:
- eval "${MATRIX_EVAL}"
script:
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=${HOME}/local ..
- cmake --build .
- cmake --build . --target install
- ctest -V
branches:
  except:
  - "/^v?\\d+\\.\\d+/"
notifications:
  email: false
  slack:
    secure: BaYUc7YsdFH+Ks7B3ddSzZA5ZaqTfRb6+trpQ2gDqALEf6VAHvjxtvHjv5Viwl+ZmWrc/ik3/u2COSKIILlgmHL9LAJutBKEH46T6IjYUyjIHyP4SdI5liSuhPE3ekH3giDFLYNpgJ5RCfPcuiO7qTO0bvjSGOfznWsfol2Fkwy+TxtLwPdDCY0haTYpcgCj4HcH1RmcPjsuJ+B5vZls0s6I853ewu8xyZZJ5O7pwkAONQfFom3WI5/VxWiJ6sEP4zx1LkrKsZmhoQPTEtQJ4Tn+7WSlsAE2io4JA1SixDfiTImNNmCIYKyrM6AyqoYwQfUJF1aLNvI8aMbfhNiiDt1p+deh8XBO2na36odOVSelqBWLrtcAlur0FZ0C7v4Bt1vVs/qPyFAYr7PIiegKMR/rhaOlMU1PJTU1jLo73BJ/xeHtSv/chIPIhYQhe/BBz+/PG6FPezJSAZ8ZrsFE+r5DUcVEZncaRPSTnqY9d4MHN3XJajmrdckjLDTibr9m/O5EXgwT2FEAVFtbfO4xm7cvsg+khV+6hDMC5bO1QtAKZ4bVRczmvmdiipkTjSS0ZvxCg98UNojn9+xlhGD0BXoJMna6znzW1HLebA0vIZhyO64KBQhMvRotUoAOOYHshZatpIKa6JDeed5lTCcz1R/mjp0tWjmJw53cr79EE/M=
